// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestService.Database;

namespace HamnetDbRest.Migrations
{
    [DbContext(typeof(QueryResultDatabaseContext))]
    partial class QueryResultDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("RestService.Database.MonitoringPerstistence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastMaintenanceEnd");

                    b.Property<DateTime>("LastMaintenanceStart");

                    b.Property<DateTime>("LastQueryEnd");

                    b.Property<DateTime>("LastQueryStart");

                    b.HasKey("Id");

                    b.ToTable("MonitoringStatus");
                });

            modelBuilder.Entity("RestService.Model.Rssi", b =>
                {
                    b.Property<string>("ForeignId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Metric")
                        .IsRequired();

                    b.Property<int>("MetricId");

                    b.Property<string>("RssiValue")
                        .IsRequired();

                    b.Property<string>("TimeStampString")
                        .IsRequired();

                    b.Property<ulong>("UnixTimeStamp");

                    b.HasKey("ForeignId");

                    b.HasIndex("ForeignId")
                        .IsUnique();

                    b.ToTable("RssiValues");
                });

            modelBuilder.Entity("RestService.Model.RssiFailingQuery", b =>
                {
                    b.Property<string>("Subnet")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ErrorInfo")
                        .IsRequired();

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Subnet");

                    b.ToTable("RssiFailingQueries");
                });
#pragma warning restore 612, 618
        }
    }
}
