// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SnmpAbstraction;

namespace SnmpAbstraction.Migrations
{
    [DbContext(typeof(CacheDatabaseContext))]
    partial class CacheDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SnmpAbstraction.CacheData", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnName("DeviceAddress");

                    b.Property<int>("ApiUsed")
                        .HasColumnName("ApiUsed");

                    b.Property<string>("DeviceHandlerClass")
                        .HasColumnName("DeviceHandlerClass");

                    b.Property<string>("InterfaceDetails")
                        .HasColumnName("InterfaceDetails");

                    b.Property<DateTime>("LastModification")
                        .HasColumnName("LastModification");

                    b.Property<string>("SystemData")
                        .HasColumnName("SystemData");

                    b.Property<string>("WirelessPeerInfos")
                        .HasColumnName("WirelessPeerInfo");

                    b.HasKey("Address");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("CacheData");
                });
#pragma warning restore 612, 618
        }
    }
}
