name: Build-Linux

on: [push]

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.401

    - name: dotnet publish
      run: dotnet publish --configuration Release -r linux-x64

    - name: Prepare Artifacts
      if: success()
      run: cp HamnetMonitoringService/bin/Release/netcoreapp2.2/linux-x64/Config/* HamnetMonitoringService/bin/Release/netcoreapp2.2/linux-x64/publish/Config

    - name: Upload Archive
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: hamnetMonitoring-linux-x64
        path: HamnetMonitoringService/bin/Release/netcoreapp2.2/linux-x64/publish
